apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: reflexcube
type: Opaque
stringData:
  POSTGRES_DB: eventdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecurepassword
  DATABASE_URL: postgresql://postgres:mysecurepassword@postgres.reflexcube.svc.cluster.local:5432/eventdb
