apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: reflexcube
data:
  SPRING_PROFILES_ACTIVE: "prod"
  APP_ENV: "production"
  FRONTEND_URL: "http://frontend-svc.reflexcube.svc.cluster.local"
